[project]
name = "mypixi"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64"]

[system-requirements]
cuda = "12.0"

[dependencies]
python = "3.11"
micro_sam = "*"
cellpose = "<4"
monai = "*"

[pypi-dependencies]
tnia-python = { git = "https://github.com/True-North-Intelligent-Algorithms/tnia-python.git" }
napari-easy-augment-batch-dl = { git = "https://github.com/True-North-Intelligent-Algorithms/napari-easy-augment-batch-dl.git" }

[target.linux-64.dependencies]
pytorch-gpu = "*"

[target.win-64.dependencies]
pytorch-gpu = "*"

[target.osx-arm64.dependencies]
pytorch = "*"  # CPU-only PyTorch for macOS

[tasks]
startup = "python startup.py"